### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by tcpipchip** [stm32-rs/stm32wlxx-hal#368]
Hi,  i want to test your gpio-blink.rs in my module LSM110A (W55JC)...

I am doing on examples folder

$~/stm32wlxx-hal
cd examples
cargo build

![image](https://github.com/stm32-rs/stm32wlxx-hal/assets/11488460/4823328f-eae1-4aae-a02b-10019f98bf54)

How i create the hex to burn in my Module ?

I dont want to use the cargo-run

Thanks

**Comment by newAM** [comment]
Building creates an ELF file (under the `target` directory).  `objcopy` can be used to change the format of that file.

**Comment by tcpipchip** [comment]
hi, but wich name ?

**Comment by tcpipchip** [comment]
well, solved...
I did a blog too
https://lom204-cli-wisol.blogspot.com/2023/09/lsm110a-blink-led-com-rust.html

**Comment by newAM** [comment]
Glad you got it working!  Sorry I couldn't provide the path earlier, I'm away from my computer for another week.

I'll close to issue now, but feel free to reopen!
